language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-user ./udagram-api-user/
  - docker tag udagram-api-user tohuy/udagram-api-user:v1
  - docker build -t udagram-api-feed ./udagram-api-feed/
  - docker tag udagram-api-feed tohuy/udagram-api-feed:v1
  - docker build -t udagram-frontend ./udagram-frontend/
  - docker tag udagram-frontend tohuy/udagram-frontend:v1
  - docker build -t reverseproxy ./reverseproxy/
  - docker tag reverseproxy tohuy/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tohuy/udagram-api-user
  - docker push tohuy/udagram-api-feed
  - docker push tohuy/udagram-frontend
  - docker push tohuy/reverseproxy