version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: tohuy/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: tohuy/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed  
    image: tohuy/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend  
    image: tohuy/udagram-frontend